id: gcp_cloud_function
$schema: gcp_schema_v_1_0.json
version: 0.0.1
technology:
  name: Google Cloud Function
minDynatraceVersion: 1.199

gcp:
- featureSet: cloud_function
  service: cloud_function
  group: cloudfunctions.googleapis.com
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.function_name
    id: function_name
  - value: resource.labels.region
    id: region
  metrics:
  - value: cloudfunctions.googleapis.com/function/active_instances
    id: cloud.gcp.cloudfunctions_googleapis_com.function.active_instances
    type: gauge
    name: Active instances
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: cloudfunctions.googleapis.com/function/execution_count
    id: cloud.gcp.cloudfunctions_googleapis_com.function.execution_count
    type: count,delta
    name: Executions
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.status
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/execution_times
    id: cloud.gcp.cloudfunctions_googleapis_com.function.execution_times
    type: gauge
    name: Execution times
    unit: ns
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.status
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/network_egress
    id: cloud.gcp.cloudfunctions_googleapis_com.function.network_egress
    type: count,delta
    name: Network egress
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/user_memory_bytes
    id: cloud.gcp.cloudfunctions_googleapis_com.function.user_memory_bytes
    type: gauge
    name: Memory usage
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.trigger_type

alerting:
  - name: "Function failures"
    description: "Cloud function failures occured"
    ##query: "avg:host.cpu:dimenions(extension_name=$this & serialNumber={{snmpDeviceSerialNumber}}).rollup(5min)" -to do confirm this alerting format / vsMINT
    query: "cloud.gcp.cloudfunctions_googleapis_com.function.execution_count"
    aggregationType: VALUE
    event_type: info
    metricDimensions:
      filterType: STRING
      key: status
      textFilter:
        value: "crash"
        operator: EQUALS
    model:
      type: STATIC_THRESHOLD #alternative baseline
      alertCondition: ABOVE
      samples: 5
      dealertingSamples: 3
      violatingSamples: 3
      threshold: 0
      unit: UNSPECIFIED

dashboards:
  - dashboard: "dashboards/cloud_function.json"