id: gcp_gcs_bucket
version: 0.0.1
technology:
  name: Google Cloud Storage
minDynatraceVersion: 1.199
gcp:
- featureSet: gcs_bucket
  group: firebasestorage.googleapis.com
  service: gcs_bucket
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.bucket_name
    id: bucket_name
  - value: resource.labels.location
    id: location
  metrics:
  - value: firebasestorage.googleapis.com/rules/evaluation_count
    id: cloud.gcp.firebasestorage_googleapis_com.rules.evaluation_count
    type: count,delta
    name: Rule evaluations
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_method
    - value: metric.labels.ruleset_label
    - value: metric.labels.result
- featureSet: gcs_bucket
  group: storage.googleapis.com
  service: gcs_bucket
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.bucket_name
    id: bucket_name
  - value: resource.labels.location
    id: location
  metrics:    
  - value: storage.googleapis.com/api/request_count
    id: cloud.gcp.storage_googleapis_com.api.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/authn/authentication_count
    id: cloud.gcp.storage_googleapis_com.authn.authentication_count
    type: count,delta
    name: Authentication count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.authentication_method
    - value: metric.labels.response_code
    - value: metric.labels.method
    - value: metric.labels.access_id
  - value: storage.googleapis.com/authz/acl_based_object_access_count
    id: cloud.gcp.storage_googleapis_com.authz.acl_based_object_access_count
    type: count,delta
    name: Object-ACL based access count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: storage.googleapis.com/authz/acl_operations_count
    id: cloud.gcp.storage_googleapis_com.authz.acl_operations_count
    type: count,delta
    name: ACLs usage
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.acl_operation
  - value: storage.googleapis.com/authz/object_specific_acl_mutation_count
    id: cloud.gcp.storage_googleapis_com.authz.object_specific_acl_mutation_count
    type: count,delta
    name: Object ACL changes
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: storage.googleapis.com/network/received_bytes_count
    id: cloud.gcp.storage_googleapis_com.network.received_bytes_count
    type: count,delta
    name: Received bytes
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/network/sent_bytes_count
    id: cloud.gcp.storage_googleapis_com.network.sent_bytes_count
    type: count,delta
    name: Sent bytes
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/storage/object_count
    id: cloud.gcp.storage_googleapis_com.storage.object_count
    type: gauge
    name: Object count
    unit: '1'
    gcpOptions:
      ingestDelay: 600s
      samplePeriod: 300s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_class
  - value: storage.googleapis.com/storage/total_byte_seconds
    id: cloud.gcp.storage_googleapis_com.storage.total_byte_seconds
    type: gauge
    name: Total byte seconds
    unit: By.s
    gcpOptions:
      ingestDelay: 600s
      samplePeriod: 300s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_class
  - value: storage.googleapis.com/storage/total_bytes
    id: cloud.gcp.storage_googleapis_com.storage.total_bytes
    type: gauge
    name: Total bytes
    unit: By
    gcpOptions:
      ingestDelay: 600s
      samplePeriod: 300s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_class
dashboards:
  - dashboard: "dashboards/gcs_bucket.json"